export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const FORM = '/form';
export const HOME = '/home';
export const CART = '/cart'
export const CART_ORDER = '/cart/order'
export const PRODUCT = '/product/:id';
export const CREATE_PRODUCT = '/product/form';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const PASSWORD_FORGET = '/pw-forget';
export const PRODUCTS = '/productlist';
export const STOCK = '/admin/stock'
export const PASSWORD_CHANGE = '/pw-change';
export const PRODDETAIL = '/productdetail';
export const MANAGE_USERS ='/manage-users';
export const ABOUT ='/about';
